Added the ability to delete a song from the queue
codeplexnl/slack-spotify-bot pull request #2
Opened 2017-10-07 00:15 UTC by ykz89

The !delete command shares the wait time with !next.

2017-10-09 06:58 UTC, codeplexnl approved these changes

2017-10-09 12:33 UTC, codeplexnl requested changes

2017-10-09 12:33 UTC, codeplexnl commented on Spotify.py
> +queueLength = 5
This can be placed in the config

2017-10-09 12:33 UTC, codeplexnl commented on Spotify.py
>              command = message[len(COMMAND_PREFIX):]
This will not work if you use params

2017-10-09 12:33 UTC, codeplexnl commented on Spotify.py
> +            numParam = int(filter(str.isdigit, message))
This is only extractable after we know which command we want to execute.

2017-10-09 12:33 UTC, codeplexnl commented on Spotify.py
> +                    numbers += "\n{}".format(str(index) + ". " + number)
correctly use the format method

2017-10-09 12:33 UTC, codeplexnl commented on Spotify.py
> +                index = 1
To get the index maybe use enumerate

https://stackoverflow.com/questions/522563/accessing-the-index-in-python-for-loops

2017-10-09 12:33 UTC, codeplexnl commented on Spotify.py
> +                    return "Please choose a number between 1-" + str(config.QUEUE_LENGTH)
use the format method

2017-10-09 12:33 UTC, codeplexnl commented on Spotify.py
> +                    Spotify.execute_command("del")
del what?

2017-10-09 16:16 UTC, ykz89 commented on Spotify.py
> +queueLength = 5
Moved to config

2017-10-09 16:19 UTC, ykz89 commented on Spotify.py
>              command = message[len(COMMAND_PREFIX):]
Changed to work with params

2017-10-09 16:19 UTC, ykz89 commented on Spotify.py
> +            numParam = int(filter(str.isdigit, message))
Cahnegd

2017-10-09 16:19 UTC, ykz89 commented on Spotify.py
> +                index = 1
removed index and used enumerate

2017-10-09 16:20 UTC, ykz89 commented on Spotify.py
> +                    numbers += "\n{}".format(str(index) + ". " + number)
cahnged

2017-10-09 16:20 UTC, ykz89 commented on Spotify.py
> +                    return "Please choose a number between 1-" + str(config.QUEUE_LENGTH)
changed

2017-10-09 16:20 UTC, ykz89 commented on Spotify.py
> +                    Spotify.execute_command("del")
frikandel

2017-10-09 19:56 UTC, codeplexnl requested changes

2017-10-09 19:56 UTC, codeplexnl commented on Spotify.py
> +                param_second = param.partition(' ')[2]
ik denk dat je beter dit kan doen 
 `param_first, param_second = param.split(' ')`

2017-10-10 06:21 UTC, codeplexnl approved these changes

2017-10-10 06:21 UTC, merged